no results if not run / clear results on most changes
exception: just typing won't clear the result because you might
want to refer to your errors in that case.

fixes #603
fixes #714